version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.2-stretch
    steps:
    - checkout
    - run: composer validate --strict
    - run: composer install
    - run: composer outdated --direct
    - run: vendor/bin/phpcs --standard=PSR12NeutronRuleset --exclude=PSR1.Classes.ClassDeclaration src/
    - run: php -d memory_limit=1G vendor/bin/phpstan analyze
workflows:
  version: 2
  workflow:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
